# Generated by Django 5.2 on 2025-06-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.IntegerField(choices=[(1, 'cliente'), (2, 'vendedor')], default=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='seller_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
