# Generated by Django 5.2 on 2025-04-23 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emovepro', '0002_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField(default=0)),
                ('cor', models.CharField(max_length=20)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('tamanho', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='emovepro.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='emovepro.marca')),
            ],
        ),
    ]
